name: Build and Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            name: pass-vault-linux-amd64
          - goos: linux
            goarch: arm64
            name: pass-vault-linux-arm64
          - goos: windows
            goarch: amd64
            name: pass-vault-windows-amd64.exe
          - goos: darwin
            goarch: amd64
            name: pass-vault-darwin-amd64
          - goos: darwin
            goarch: arm64
            name: pass-vault-darwin-arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -v -ldflags="-s -w" -o ${{ matrix.name }} .
    
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}